# -*- coding: utf-8 -*-
"""solar task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TkwGu5kqZgB0gCbGPp36bc7TyqVkg-ek
"""

# drive mount
from google.colab import drive
drive.mount('/content/drive')

data.info()

data.describe()

data.isna().sum()

data = data.dropna()

data["Gender"].unique()

data["Gender"].value_counts()

data.duplicated().sum()

data= data.drop_duplicates()

data["Gender"].unique()

data["Gender"]=data["Gender"].str.lower()

data["Gender"]=data["Gender"].str.strip()

data["Education Level"].unique()

data["Equcation Level"]=data["Education Level"].str.lower()

replace_edu={
    "Bachelors":"Bachelor's",
    "Masters":"masters's"
}
data["Education Level"]=data["Education Level"].replace(replace_edu)

data["Education Level"].unique()

data["Education Level"]=data["Education Level"].str.lower()

replace_edu={
    "bachelor's":"bachelor's degree",
    "masters's":"masters's degree"
}
data["Education Level"]=data["Education Level"].replace(replace_edu)
data["Education Level"].unique()

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data["Salary"],color="red")
plt.title("salary distribution")
plt.show()

sns.histplot(data["Age"],color="blue")
plt.title("age distribution")
plt.show()

data["Age"].unique()

data=data[(data["Age"]>16) & (data["Age"]<60)]

sns.histplot(data["Years of Experience"],color="green",bins=20,kde=True)
plt.title("years of experience distribution")
plt.show()

sns.countplot(data["Gender"],color="orange")
plt.title("gender distribution ")
plt.show()

sns.countplot(data["Education Level"],color="purple")
plt.title("education level distribution")
plt.show()

sns.boxenplot(data["Age"],color="skyblue")
plt.show()

sns.boxenplot(data["Salary"],color="brown")
plt.show()

sns.boxenplot(data["Years of Experience"],color="green")
plt.show()



# scatterplot
sns.scatterplot(data=data,x="Years of Experience",y="Salary")
plt.title("scatterplot between years of age and salary")
plt.show()

sns.scatterplot(data=data,x="Years of Experience",y="Salary")
plt.title("scatterplot between years of age and salary")
plt.show()





from google.colab import drive
drive.mount('/content/drive')

filepath="/content/drive/MyDrive/solar power gen.zip"

import pandas as pd

data=pd.read_csv(filepath)

data.head(5)

import numpy as np
data.duplicated().sum()
np.int64(0)

income = float(input("Enter your income: "))

if income < 30000:
    tax = income * 0.05
elif income <= 60000:
    tax = income * 0.10
elif income <= 100000:
    tax = income * 0.15
else:
    tax = income * 0.20

print("Tax amount:", tax)

bill = float(input("Enter your shopping bill amount: "))

if bill >= 5000:
    discount = bill * 0.20
elif bill >= 2000:
    discount = bill * 0.10
elif bill >= 1000:
    discount = bill * 0.05
else:
    discount = 0

print("Discount amount:", discount)
print("Final amount to pay:", bill - discount)

data.info()

data.describe()

data.isna().sum()

data = data.dropna()

data["Sky Cover"].unique()

data["Sky Cover"].value_counts()

data.duplicated().sum()

data= data.drop_duplicates()

data["Sky Cover"].unique()

data["Month"].unique()

data["Sky Cover"]=data["Sky Cover"]

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(data["Sky Cover"],color="red")
plt.title("sky cover")
plt.show()

sns.histplot(data["Year"],color="blue")
plt.title("year distribution")
plt.show()

data["Month"].unique()

sns.histplot(data["Day of Year"],color="green",bins=20,kde=True)
plt.title("day of year distribution")
plt.show()

sns.countplot(data["Is Daylight"],color="orange")
plt.title("Is Daylight distribution")
plt.show()

sns.countplot(data["Sky Cover"],color="purple")
plt.title("month")
plt.show()

sns.boxenplot(data["Day"],color="skyblue")
plt.show()

sns.boxenplot(data["Sky Cover"],color="brown")
plt.show()

sns.boxenplot(data["Month"],color="green")
plt.show()

# scatterplot
sns.scatterplot(data=data,x="Sky Cover",y="Day")
plt.title("scatterplot sky cover of and day")
plt.show()

sns.scatterplot(data=data,x="Sky Cover",y="Day")
plt.title("scatterplot between sky cover and day")
plt.show()







"""hw
8-2-2026

"""

# drive mount
from google.colab import drive
drive.mount('/content/drive')

filepath="/content/drive/MyDrive/solar power gen.zip"

import pandas as pd
data=pd.read_csv(filepath, compression='zip')
#label encoding
from sklearn.preprocessing import LabelEncoder
#le=label encoder()
##data["education level"]=le.fit_transform(data["education level"])
label_encode={}
for col in data.select_dtypes(include="object").columns:
  le=LabelEncoder()
  data[col]=le.fit_transform(data[col])
  label_encode[col]=le

data = data.dropna()

data.info()

import matplotlib.pyplot as plt
import seaborn as sns
sns.heatmap(data.corr(),annot=True,cmap="Blues")
plt.show()

data.skew(numeric_only=True)

data.duplicated().sum()

data= data.drop_duplicates()

data = data.dropna()

#splitting data into features and target  variable
x=data.drop("Power Generated",axis=1)
y=data["Power Generated"]
x.head()

#splitting in train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred_lr=lr.predict(x_test)

#decision tree regressor
from sklearn.metrics import r2_score
r2_lr=r2_score(y_test,y_pred_lr)
print(r2_lr)

#randomforest regressor
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()

#downloading the model
import joblib
joblib.dump(rfr,"solar_power.pkl")

# download in system
import joblib
from google.colab import files
from sklearn.ensemble import RandomForestRegressor

# Ensure the model (rfr) is defined and dump it before downloading
# If 'rfr' was not defined from previous cells (e.g., due to kernel restart),
# it needs to be initialized. Note: This model is not yet fitted.
if 'rfr' not in locals() and 'rfr' not in globals():
    rfr = RandomForestRegressor()

joblib.dump(rfr, "solar_power.pkl")
files.download("solar_power.pkl")

#download in system
from google.colab import files
files.download("solar_power.pkl")





"""new section 15 feb"""

























